services:
  nginx:
    image: nginx:1.27.0
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - n2app-file-networks

networks:
  n2app-file-networks:
    external: true
    name: n2app-file-networks
